window.ClimaMap = (() => {
  let map = null, fallback = null, markers = null, currentFeatures = [], currentLayer = "temperature", onSelect = () => {};
  const colors = { temperature: "#f0a52f", rainfall: "#39a5ff", humidity: "#35e5b0", prediction: "#bd6bff", scenario: "#ff668c" };
  const center = [78.9629, 22.5937];
  const style = { version: 8, sources: { osm: { type: "raster", tiles: ["https://tile.openstreetmap.org/{z}/{x}/{y}.png"], tileSize: 256, attribution: "© OpenStreetMap contributors" } }, layers: [{ id: "osm", type: "raster", source: "osm", paint: { "raster-saturation": -0.55, "raster-contrast": 0.15, "raster-brightness-max": 0.72 } }] };
  function popupHtml(p) { return `<strong>${p.location_name || "Selected location"}</strong><br>Temperature: ${p.temperature ?? "N/A"}<br>Rainfall: ${p.rainfall ?? "N/A"}<br>Humidity: ${p.humidity ?? "N/A"}<br>Time: ${p.timestamp || "N/A"}<br>Source: ${p.source || "LOCAL"}`; }
  function init() {
    const el = document.getElementById("map");
    if (window.maplibregl && el) { try { map = new maplibregl.Map({ container: el, style, center, zoom: 4.35, pitch: 48, bearing: -8, maxPitch: 60 }); map.addControl(new maplibregl.NavigationControl({ showCompass: true }), "top-left"); map.on("load", () => { addSource(); render(currentFeatures, currentLayer, onSelect); }); } catch (_) { showFallback(); } }
    else showFallback();
    document.getElementById("map-tilt")?.addEventListener("click", () => { if (map) map.easeTo({ pitch: map.getPitch() > 10 ? 0 : 52, duration: 700 }); });
    document.getElementById("map-reset")?.addEventListener("click", () => { if (map) map.easeTo({ center, zoom: 4.35, pitch: 48, bearing: -8, duration: 700 }); });
    document.getElementById("map-fullscreen")?.addEventListener("click", () => { const node = document.getElementById("map-section"); if (node?.requestFullscreen) node.requestFullscreen(); });
  }
  function showFallback() { const node = document.getElementById("map-fallback"); if (node) node.hidden = false; if (window.L) { fallback = L.map("map").setView([22.6, 78.9], 5); L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png", { attribution: "© OpenStreetMap contributors" }).addTo(fallback); markers = L.layerGroup().addTo(fallback); } }
  function addSource() { if (!map || map.getSource("climate-observations")) return; map.addSource("climate-observations", { type: "geojson", data: { type: "FeatureCollection", features: [] } }); map.addLayer({ id: "climate-points", type: "circle", source: "climate-observations", paint: { "circle-radius": ["interpolate", ["linear"], ["zoom"], 3, 5, 8, 12], "circle-color": colors.temperature, "circle-stroke-color": "#d9ffff", "circle-stroke-width": 1, "circle-opacity": 0.9, "circle-blur": 0.18 } }); map.on("click", "climate-points", e => { const f = e.features?.[0]; if (!f) return; new maplibregl.Popup({ closeButton: true }).setLngLat(f.geometry.coordinates).setHTML(popupHtml(f.properties)).addTo(map); onSelect(f.properties.location_id); }); map.on("mouseenter", "climate-points", () => { map.getCanvas().style.cursor = "pointer"; }); map.on("mouseleave", "climate-points", () => { map.getCanvas().style.cursor = ""; }); }
  function render(features, layer, select) { currentFeatures = features || []; currentLayer = layer || "temperature"; onSelect = select || (() => {}); const valueKey = ["temperature", "rainfall", "humidity"].includes(currentLayer) ? currentLayer : "temperature"; const visible = currentFeatures.filter(f => f.properties?.[valueKey] !== null && f.properties?.[valueKey] !== undefined); const data = { type: "FeatureCollection", features: visible }; const legend = document.getElementById("map-legend-label"); if (legend) legend.textContent = `${valueKey[0].toUpperCase() + valueKey.slice(1)} (${valueKey === "humidity" ? "%" : valueKey === "rainfall" ? "mm" : "°C"})`; if (map) { if (!map.isStyleLoaded()) { map.once("load", () => render(features, layer, select)); return; } addSource(); map.getSource("climate-observations").setData(data); map.setPaintProperty("climate-points", "circle-color", colors[currentLayer] || colors.temperature); if (visible.length) { const lngs = visible.map(f => f.geometry.coordinates[0]), lats = visible.map(f => f.geometry.coordinates[1]); map.fitBounds([[Math.min(...lngs), Math.min(...lats)], [Math.max(...lngs), Math.max(...lats)]], { padding: 40, maxZoom: 8, duration: 600 }); } } else if (fallback && markers) { markers.clearLayers(); visible.forEach(f => { const p = f.properties, c = f.geometry.coordinates; L.circleMarker([c[1], c[0]], { radius: 8, color: colors[currentLayer], fillColor: colors[currentLayer], fillOpacity: .85 }).bindPopup(popupHtml(p)).on("click", () => select(p.location_id)).addTo(markers); }); } }
  function focus(lat, lon) { if (map) map.flyTo({ center: [lon, lat], zoom: 7.5, pitch: 52, duration: 700 }); else if (fallback) fallback.flyTo([lat, lon], 8); }
  return { init, render, focus };
})();
