/* Data-bound spherical digital twin. Geographic outlines come from public GeoJSON; climate points come from Flask. */
window.ClimaTwin3D = (() => {
  let scene, camera, renderer, controls, globe, marker, pulse, continentGroup, dataGroup, animationId;
  const radius = 1.35;
  const latLonToVector = (lat, lon, r = radius) => { const phi = (90 - Number(lat)) * Math.PI / 180; const theta = (Number(lon) + 180) * Math.PI / 180; return new THREE.Vector3(-r * Math.sin(phi) * Math.cos(theta), r * Math.cos(phi), r * Math.sin(phi) * Math.sin(theta)); };
  function init() { const canvas = document.getElementById("twin-globe"); if (!canvas || !window.THREE) return; const parent = canvas.parentElement, width = parent.clientWidth || 170, height = parent.clientHeight || 150; scene = new THREE.Scene(); camera = new THREE.PerspectiveCamera(34, width / height, .1, 100); camera.position.set(0, .15, 4.1); renderer = new THREE.WebGLRenderer({ canvas, antialias: true, alpha: true }); renderer.setPixelRatio(Math.min(window.devicePixelRatio || 1, 2)); renderer.setSize(width, height, false); renderer.setClearColor(0x020b18, 0); scene.add(new THREE.AmbientLight(0x4b8ebc, 1.5)); scene.add(new THREE.PointLight(0x38d6ff, 2, 8));
    globe = new THREE.Mesh(new THREE.SphereGeometry(radius, 64, 40), new THREE.MeshPhongMaterial({ color: 0x083257, emissive: 0x021120, shininess: 35, transparent: true, opacity: .94 })); scene.add(globe); const wire = new THREE.Mesh(new THREE.SphereGeometry(radius * 1.002, 32, 20), new THREE.MeshBasicMaterial({ color: 0x2abedc, wireframe: true, transparent: true, opacity: .16 })); scene.add(wire);
    const atmosphere = new THREE.Mesh(new THREE.SphereGeometry(radius * 1.08, 48, 32), new THREE.MeshBasicMaterial({ color: 0x26d8ff, transparent: true, opacity: .11, side: THREE.BackSide })); scene.add(atmosphere); const ring = new THREE.Mesh(new THREE.TorusGeometry(radius * 1.27, .008, 8, 128), new THREE.MeshBasicMaterial({ color: 0x33c9e8, transparent: true, opacity: .65 })); ring.rotation.x = Math.PI / 2.7; scene.add(ring); pulse = new THREE.Mesh(new THREE.RingGeometry(.08, .095, 32), new THREE.MeshBasicMaterial({ color: 0x48edff, transparent: true, opacity: .95, side: THREE.DoubleSide })); scene.add(pulse);
    if (THREE.OrbitControls) { controls = new THREE.OrbitControls(camera, renderer.domElement); controls.enablePan = false; controls.enableDamping = true; controls.enableZoom = true; controls.minDistance = 3.2; controls.maxDistance = 5; } window.addEventListener("resize", resize); animate(); loadContinents(); }
  function resize() { if (!renderer) return; const parent = renderer.domElement.parentElement, width = parent.clientWidth || 170, height = parent.clientHeight || 150; camera.aspect = width / height; camera.updateProjectionMatrix(); renderer.setSize(width, height, false); }
  function addOutline(coords, color, lineWidth = 1) { const points = coords.map(([lon, lat]) => latLonToVector(lat, lon, radius * 1.012)); if (points.length < 2) return; const line = new THREE.Line(new THREE.BufferGeometry().setFromPoints(points), new THREE.LineBasicMaterial({ color, transparent: true, opacity: .9, linewidth: lineWidth })); continentGroup.add(line); }
  async function loadContinents() { if (!scene) return; continentGroup = new THREE.Group(); scene.add(continentGroup); try { const response = await fetch("https://raw.githubusercontent.com/johan/world.geo.json/master/countries.geo.json"); if (!response.ok) throw new Error("geography unavailable"); const geo = await response.json(); geo.features.forEach(feature => { const name = String(feature.properties?.name || "").toLowerCase(); const color = name === "india" ? 0x64f279 : 0x74b7c7; const geometry = feature.geometry; if (geometry.type === "Polygon") geometry.coordinates.forEach(ring => addOutline(ring, color)); if (geometry.type === "MultiPolygon") geometry.coordinates.forEach(poly => poly.forEach(ring => addOutline(ring, color))); }); } catch (_) { /* Globe remains functional with surface/grid fallback. */ } }
  function setLocation(lat, lon) { if (!scene || !pulse || !Number.isFinite(Number(lat)) || !Number.isFinite(Number(lon))) return; const position = latLonToVector(lat, lon, radius * 1.035); pulse.position.copy(position); pulse.lookAt(0, 0, 0); if (!marker) { marker = new THREE.Mesh(new THREE.SphereGeometry(.055, 16, 12), new THREE.MeshBasicMaterial({ color: 0x69ff76 })); scene.add(marker); } marker.position.copy(position); }
  function setClimatePoints(features) { if (!scene) return; if (dataGroup) scene.remove(dataGroup); dataGroup = new THREE.Group(); (features || []).forEach(feature => { const p = feature.properties || {}, c = feature.geometry?.coordinates || []; if (!Number.isFinite(Number(c[1])) || !Number.isFinite(Number(c[0]))) return; const point = new THREE.Mesh(new THREE.SphereGeometry(.025, 8, 6), new THREE.MeshBasicMaterial({ color: p.temperature == null ? 0x39c9ff : 0xffb842 })); point.position.copy(latLonToVector(c[1], c[0], radius * 1.025)); dataGroup.add(point); }); scene.add(dataGroup); }
  function animate() { animationId = requestAnimationFrame(animate); if (globe) globe.rotation.y += .0012; if (continentGroup) continentGroup.rotation.y += .0012; if (dataGroup) dataGroup.rotation.y += .0012; if (pulse) { const s = 1 + Math.sin(Date.now() * .004) * .12; pulse.scale.setScalar(s); } if (controls) controls.update(); renderer?.render(scene, camera); }
  function dispose() { cancelAnimationFrame(animationId); renderer?.dispose(); }
  return { init, setLocation, setClimatePoints, dispose };
})();
